version: '3'


services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/public/:/etc/nginx/public/
      - ./ssl/certs/:/etc/pki/tls/certs/
      - ./ssl/private/:/etc/pki/tls/private/
    depends_on:
      - app
    networks:
      - network

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app:/var/www/
    depends_on:
      - mongo
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
      TZ: Asia/Tokyo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/"

networks:
  network:
    driver: bridge